package(default_visibility = ["//visibility:public"])
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")

closure_js_library(
  name = "singly",
  srcs = ["SingleLinkedList.js","SinglyLinkedNode.js", "TailedSingleLinkedList.js"],
  deps = [
    "@io_bazel_rules_closure//closure/library"
  ]
)
