package(default_visibility = ["//visibility:public"])
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")

closure_js_library(
  name = "list",
  srcs = ["List.js"],
  deps = [
    "@io_bazel_rules_closure//closure/library"
    ,"//list/singly"
    ,"//list/doubly"
  ]
)
